name: flutter_modularized
packages:
  - apps/*
  - packages/*

sdkPath: .fvm/flutter_sdk

scripts:
  analyze:
    exec: dart analyze .

  clear:
    exec: flutter clean

  generate:
    exec:
      concurrency: 1
    packageFilters:
      scope: feature_movie
    run: flutter pub run build_runner build --delete-conflicting-outputs
