name: admin_app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8

  flutter_bloc: 9.1.0
  go_router: 14.8.1
  firebase_auth: 5.5.1
  firebase_ui_auth: 1.16.1
  firebase_core: 3.12.1
  firebase_remote_config: 5.4.2
  cloud_firestore: 5.6.5
  get_it: 8.0.3

  authentication:
    path: ../../packages/authentication

  core:
    path: ../../packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
