name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  logger: 2.5.0
  intl: 0.19.0
  dio: 5.7.0
  retrofit: 4.4.2
  shimmer: 3.0.0
  package_info_plus: 8.3.0

  ## Riverpod
  hooks_riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  flutter_hooks: 0.21.2
  riverpod_annotation: 2.6.1

flutter:
  assets:
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
