name: feature_movie
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: 5.2.1
  dio: 5.7.0
  retrofit: 4.4.2
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4

  core:
    path: ../core

flutter:
  assets:
    - .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: 2.4.13
  json_serializable: 6.9.0
  freezed: 2.5.7